#!/usr/bin/env bash
# Configures Nginx to run as nginx user on port 8080
id -u nginx &>/dev/null || useradd --no-create-home --shell /bin/false nginx
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server ipv6only=on/listen [::]:8080 default_server ipv6only=on/' /etc/nginx/sites-available/default
nginx -s stop 2>/dev/null || kill "$(cat /var/run/nginx.pid)" 2>/dev/null || true
sleep 1
/usr/sbin/nginx
