#!/usr/bin/env bash
#Installs Nginx on the server
apt-get -y update
apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
echo "Holberton School for the win!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm 404.html index.nginx-debian.html;
	server_name _;
	add_header X-Served-By $HOSTNAME;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=-VGIt10m9VQ;
	}
	location /xyz {
		return 404;
	}
	error_page 404 /404.html;
}" > /etc/nginx/sites-available/default
sudo chown -R root:root /var/www/html
sudo chown -R root:root /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload