#!/usr/bin/env bash
# Script to transfer a file from the local machine to the remote server using scp

# Check if exactly 4 arguments were passed
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

#Create the parameters
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# transfer file
# scp [options] source destination
scp -i "$PATH_TO_SSH_KEY" \
    -o StrictHostKeyChecking=no \
    "$PATH_TO_FILE" \
    "$USERNAME@$IP:~/"