#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page
# The redirection is a "301 Moved Permanently"

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Add redirect rule for /redirect_me using string replacement (more reliable)
new_string="server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://cinemora-cyan.vercel.app;\n\t}\n"
sudo sed -i "s|server_name _;|$new_string|" /etc/nginx/sites-available/default

sudo service nginx restart