#!/usr/bin/env bash
# Configures nginx to redirect /redirect_me to another page with 301
apt-get update -y
apt-get install nginx -y
echo "Holberton School" | tee /var/www/html/index.html > /dev/null
sed -i 's|server_name _;|server_name _;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;|' /etc/nginx/sites-available/default
service nginx start