#!/usr/bin/env bash
# Configures Nginx to use a custom 404 page

# Install nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Allow HTTP through firewall
sudo ufw allow 'Nginx HTTP'

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Configure nginx to use custom 404 page
sudo sed -i "s|server_name _;|server_name _;\n\terror_page 404 /404.html;|" /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart